name: Testing GH action
on:
  issues:
    types:
      - opened

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: lisadean/the-sorting-hat@replace-original-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
