name: Testing GH action
on:
  pull_request:

jobs:
  LabelPR:
    runs-on: ubuntu-latest
    steps:
      - uses: lisadean/the-sorting-hat@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
